on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
        echo "${{ toJSON(github.event.inputs) }}"
        mkdir -p path/to/artifact
        echo "${{ toJSON(github.event.inputs) }}" > path/to/artifact/parameters.json
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: path/to/artifact/parameters.json

